# CID DE NIVEL 3 - Disparo automático sempre que outro for concluído, como deploy

#nome que vai aparecer la nas opções de pipe
name: 'Execução por Deploy'

#regras de disparo da execução (triggers/gatilhos)
# gatilho de exec apos outro workflow = workflow_run

on:
  workflow_run:
    workflows: ['Execução manual']
    types:
      - completed

jobs:
  # descrição do job
  e2e-tests:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    #passo a passo das ações do job
    steps:
      - uses: actions/checkout@v4

      - name: Instalado Yarn
        run: npm install -g yarn

      - name: Instalado dependências
        run: yarn

      - name: Instalado Playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled()}}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
