# CID DE NIVEL 4 - Disparo dentro do fluxo de Ci de desenvolvimento

#nome que vai aparecer la nas opções de pipe
name: 'Execução Integrada'

#Trigges ou gatilhos de execução
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:
  # descrição do job

  inspection:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalado Yarn
        run: npm install -g yarn

      - name: Instalado dependências
        run: yarn

      - name: Padronizacao de codigo (Lint)
        run: yarn lint

  unit:
    runs-on: ['ubuntu-latest']
    needs: [inspection]
    steps:
      - uses: actions/checkout@v4

      - name: Instalado Yarn
        run: npm install -g yarn

      - name: Instalado dependências
        run: yarn

      - name: Testes de Unidade
        run: yarn run test

  e2e-tests:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']
    needs: [unit]
    #passo a passo das ações do job
    steps:
      - uses: actions/checkout@v4

      - name: Instalado Yarn
        run: npm install -g yarn

      - name: Instalado dependências
        run: yarn

      - name: Instalado Playwright
        run: yarn playwright install

      - name: Subir aplicacao local
        run: yarn start &
        env:
          URL: 'http://localhost:3000/'

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled()}}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

  deploy:
    runs-on: ['ubuntu-latest']
    needs: [e2e-tests]

    steps:
      - name: Deploy
        run: echo "step deploy"
